name: training_face
version: 0.1.0
display_name: Training an AI model
type: command
description: Trains an AI model by inputting a lot of training and testing data.

code: ./code
environment: azureml:aml-Tensorflow-Pillow:0.1.0
command: "python train.py             --training_folder ${{inputs.training_folder}}             --testing_folder ${{inputs.testing_folder}}
  --output_folder ${{outputs.output_folder}}             --epochs ${{inputs.epochs}}             "

inputs:
  training_folder:
    type: uri_folder
    optional: False
  testing_folder:
    type: uri_folder
    optional: False
  epochs:
    type: number
    optional: False
outputs:
  output_folder:
    type: uri_folder
